name: spotify_clone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
#  sdk: ^3.8.1
   sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc:
  flutter_bloc:
  shared_preferences:
  sizer:
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SpotifyMix
      fonts:
        - asset: assets/fonts/SpotifyMix-Thin.ttf
          weight: 100
        - asset: assets/fonts/SpotifyMix-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/SpotifyMix-Light.ttf
          weight: 300
        - asset: assets/fonts/SpotifyMix-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SpotifyMix-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpotifyMix-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/SpotifyMix-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpotifyMix-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SpotifyMix-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpotifyMix-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SpotifyMix-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/SpotifyMix-ExtraboldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/SpotifyMix-Black.ttf
          weight: 900
        - asset: assets/fonts/SpotifyMix-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/SpotifyMix-Ultra.ttf
          weight: 900
        - asset: assets/fonts/SpotifyMix-UltraItalic.ttf
          weight: 900
          style: italic
